import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Mirror the rendered context to <repo>/.kireo/CONTEXT.md.
 *
 * This is the degraded surface: it can be @-referenced, read by a human, and
 * survives any MCP or network failure. Cheap to write, and the only thing that
 * still works when everything else does not.
 */
export const writeContextMd = (repoRoot: string, body: string): string => {
  const dir = join(repoRoot, '.kireo');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'CONTEXT.md');
  writeFileSync(path, `<!-- generated by kireo · do not edit by hand -->\n\n${body}\n`);
  return path;
};
